### ISSUE TITLE
Allow user to set cronjob for the emptying of trash can

### ISSUE THREAD

**Issue by HarrisonHemstreet** [AmineZouitine/rmt.rs#31]
Make the config.yml file look something like so:
```yml
compression: true

trash:
    max_size: 10000
    max_element: 10
    automatic_flush:
      time: something 
```
The user should be able to set the cron either from a file, or via a cli option
